join_message_options:
  custom_join_messages: false
  custom_first_join: '&e%player.name% has joined for their first time! &dWelcome! #%server.join_count%'
  custom_join_message: '&e%player.name% has joined the game, Welcome to our server!'
  additional_messages: false
  additional_message:
    - '&dWanna apply for staff? Click here!&n https://www.github.com/ItziSpyder'
    - '&aEnjoy your stay!'
  custom_leave_messages: false
  custom_leave_message: '&e%player.name% has left :('
