name: OgredupeAlias
version: '${version}'
main: me.improper.ogredupealias.OgredupeAlias
api-version: 1.17
authors: [ ImproperIssues, TheTelly ]
description: OgreDupe.minehut.gg! Visit orgestupe.tebex.io
website: https://github.com/ItziSpyder/PluginRequests
permissions:
  ogredupealias.chat.see:
    description: Be able to receive chat messages broadcasted by Anti-Swear.
    default: op
  ogredupealias.chat.bypass:
    description: Permission to bypass chat disabler.
    default: op
commands:
  commandspy:
    description: "Be able to see players' commands."
    usage: /commandspy
    permission: ogredupealias.chat.see
    aliases:
      - cmdspy
      - cspy
      - cs
  socialspy:
    description: "Be able to see players' private messages."
    usage: /socialspy
    permission: ogredupealias.chat.see
    aliases:
      - sspy
      - ss
  mutechat:
    description: "Mutes the chat"
    usage: /mutechat
    permission: ogredupealias.chat.bypass
  message:
    description: "Direct message a player"
    usage: /message <player> <message>
    aliases:
      - msg
      - tell
      - w
      - whisper