name: OgredupeAlias
version: '${version}'
main: me.improper.ogredupealias.OgredupeAlias
api-version: 1.17
authors: [ ImproperIssues, TheTelly ]
description: OgreDupe.minehut.gg! Visit orgestupe.tebex.io
website: https://github.com/ItziSpyder/PluginRequests
permissions:
  ogredupealias.chat.see:
    description: Be able to receive chat messages broadcasted by Anti-Swear.
    default: op
  ogredupealias.chat.bypass:
    description: Permission to bypass chat disabler.
    default: op
  ogredupealias.chat.staff:
    description: Permission to access staff chat.
    default: op
  ogredupealias.commands.tpa:
    description: Access to /tpa
  ogredupealias.commands.tpahere:
    description: Access to /tpahere
commands:
  commandspy:
    description: "Be able to see players' commands."
    usage: /commandspy
    permission: ogredupealias.chat.see
    aliases:
      - cmdspy
      - cspy
      - cs
  socialspy:
    description: "Be able to see players' private messages."
    usage: /socialspy
    permission: ogredupealias.chat.see
    aliases:
      - sspy
      - ss
  mutechat:
    description: "Mutes the chat"
    usage: /mutechat
    permission: ogredupealias.chat.bypass
  message:
    description: "Direct message a player"
    usage: /message <player> <message>
    aliases:
      - msg
      - tell
      - w
      - whisper
  staffchat:
    description: Send a message to staff chat.
    usage: /staffchat <message>
    permission: ogredupealias.chat.staff
    aliases:
      - schat
      - sc
  tpa:
    description: Send a tpa request
    usage: /tpa <player>
    permission: ogredupealias.commands.tpa
    aliases:
      - tpask
  tpahere:
    description: Send a tpahere request
    usage: /tpahere <player>
    permission: ogredupealias.commands.tpahere
    aliases:
      - tphere
  tpdeny:
    description: Deny a tp request
    permission: ogredupealias.commands.tpa
    usage: /tpdeny
  tpcancel:
    description: Cancel a tp request
    permission: ogredupealias.commands.tpa
    usage: /tpcancel
  tpaccept:
    description: Accept a tp request
    permission: ogredupealias.commands.tpa
    usage: /tpaccept